name: Go CI

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define the jobs to run
jobs:
  build:
    
    # The OS and version to run the job on
    runs-on: ubuntu-latest

    # Define the sequence of steps to execute
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: Build the backend
      working-directory: ./backend
      run: go build 
    - name: Build the frontend
      working-directory: ./frontend
      run: go build 
      
  test:
    
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: Run tests
      working-directory: ./frontend
      run: go test 
